/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tax;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ninja
 */
public class AboutForm extends javax.swing.JFrame {

    /**
     * Creates new form AboutForm
     */
    public AboutForm() {
        initComponents();
        try {
            this.setIconImage((BufferedImage) ImageIO.read(Tax.class.getResource("icons/info.png")));
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setResizable(false);
        
        iconLab.setIcon(new ImageIcon(Tax.class.getResource("icons/img/tax.png")));
        gplLab.setIcon(new ImageIcon(Tax.class.getResource("icons/img/gpl3.png")));
        text.setText("Το EnTax είναι ένα πρόγραμμα μηχανογράφησης\n"
                + "αποδείξεων για τον εν Ελλάδι φορολογούμενο.\n\n"
                + "Σχεδιάστηκε έχοντας στο νου την (κατά δύναμιν)\n"
                + "διευκόλυνση και επίσπευση της όλης διαδικασίας.");
        
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JEditorPane();
        iconBackg = new javax.swing.JPanel();
        iconLab = new javax.swing.JLabel();
        gplLab = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        copyrightLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Περί του EnTax");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setEditable(false);
        text.setFocusable(false);
        text.setOpaque(false);
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 280, 90));

        iconBackg.setBackground(new java.awt.Color(0, 0, 0));
        iconBackg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        iconBackg.add(iconLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 48, 48));

        getContentPane().add(iconBackg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 170));
        getContentPane().add(gplLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 125, 70, 38));

        jButton1.setText("ΟΚ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 137, 40, -1));

        copyrightLab.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        copyrightLab.setForeground(new java.awt.Color(153, 153, 153));
        copyrightLab.setText("©2014 Yannis Mantzas");
        getContentPane().add(copyrightLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 105, -1, -1));

        setSize(new java.awt.Dimension(395, 198));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLab;
    private javax.swing.JLabel gplLab;
    private javax.swing.JPanel iconBackg;
    private javax.swing.JLabel iconLab;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane text;
    // End of variables declaration//GEN-END:variables
}
