/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tax;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author ninja
 */
public class AliasPrompt extends javax.swing.JFrame {

    private MainForm f;
    private HashMap afmToName = new HashMap();
    /**
     * Creates new form AliasPrompt
     */
    public AliasPrompt(MainForm f) {
        initComponents();
        this.setResizable(false);
        this.f = f;
        this.afmToName = f.getAfmToName();
        afmText.setText(f.getAfmText().getText());
        
        try {
            this.setIconImage((BufferedImage) ImageIO.read(Tax.class.getResource("icons/alias.png")));
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        afmText = new javax.swing.JTextField();
        cancelBut = new javax.swing.JButton();
        okBut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Διπλότυπο ΑΦΜ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 2, 2));

        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextKeyPressed(evt);
            }
        });
        jPanel1.add(nameText);

        afmText.setEditable(false);
        afmText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(afmText);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 50));

        cancelBut.setText("Άκυρο");
        cancelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, -1));

        okBut.setText("ΟΚ");
        okBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButActionPerformed(evt);
            }
        });
        getContentPane().add(okBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 40, -1));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 2, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Όνομα");
        jPanel2.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ΑΦΜ");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        setSize(new java.awt.Dimension(204, 151));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            okBut.doClick();
        }
    }//GEN-LAST:event_nameTextKeyPressed

    private void cancelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButActionPerformed
        this.dispose();
        f.getAddRowBut().doClick();
    }//GEN-LAST:event_cancelButActionPerformed

    private void okButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButActionPerformed
        String name = nameText.getText();
        
        if (afmToName.containsKey(name) || name.equals("")) {
            nameText.setText("");
            Util.fadeInAndOut(nameText, Util.darkOrange);
        } else {
            this.dispose();
            f.getAfmTextS().setText(afmText.getText());
            f.getNameTextS().setText(nameText.getText());
            f.getAddNameBut().doClick();

            f.getNameText().setText(nameText.getText());
            f.getAddRowBut().doClick();
        }
    }//GEN-LAST:event_okButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afmText;
    private javax.swing.JButton cancelBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton okBut;
    // End of variables declaration//GEN-END:variables
}
